[package]
name = "game-of-life"
version = "0.1.0"
authors = ["LightDiscord <root@arnaud.sh>"]
edition = "2018"
categories = ["wasm"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"
